// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAW3K-Zs8kDXhqRdXMfhAD5e0jqt3jLUg',
    appId: '1:219981771801:web:afd988835947ec7e1ce688',
    messagingSenderId: '219981771801',
    projectId: 'password-generator-20d0c',
    authDomain: 'password-generator-20d0c.firebaseapp.com',
    storageBucket: 'password-generator-20d0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR_LR_uJYLXQ_GCs8W09zfwz9dx8TNnso',
    appId: '1:219981771801:android:e71347e39d6a3edd1ce688',
    messagingSenderId: '219981771801',
    projectId: 'password-generator-20d0c',
    storageBucket: 'password-generator-20d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfbOQt0x58hr-9hBI_qPN2ECy3hj3mmM',
    appId: '1:219981771801:ios:d8b30e3d1bfee1461ce688',
    messagingSenderId: '219981771801',
    projectId: 'password-generator-20d0c',
    storageBucket: 'password-generator-20d0c.appspot.com',
    iosBundleId: 'com.example.passwordGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFfbOQt0x58hr-9hBI_qPN2ECy3hj3mmM',
    appId: '1:219981771801:ios:d8b30e3d1bfee1461ce688',
    messagingSenderId: '219981771801',
    projectId: 'password-generator-20d0c',
    storageBucket: 'password-generator-20d0c.appspot.com',
    iosBundleId: 'com.example.passwordGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAW3K-Zs8kDXhqRdXMfhAD5e0jqt3jLUg',
    appId: '1:219981771801:web:cf303f27c930f3851ce688',
    messagingSenderId: '219981771801',
    projectId: 'password-generator-20d0c',
    authDomain: 'password-generator-20d0c.firebaseapp.com',
    storageBucket: 'password-generator-20d0c.appspot.com',
  );
}
